name = "nextcloud-webdav-proxy"
main = "index.js"
compatibility_date = "2024-03-01"

# Không bắt buộc, định tuyến để bỏ chặn CORS
# routes = [
#   { pattern = "wokernotmaths.hnong9367.workers.dev/*", custom_domain = true }
# ]
